map ctrl+b combine : clear_terminal active : send_text normal \x0c
#dynamic_background_opacity yes
shell_integration no-cursor
cursor_shape block
resize_in_steps yes

# special
foreground       #ffffff
#foreground_bold  #ffffff
cursor           #ffffff
background       #24283b


#font_family Perplexed-Bold 
font_family BlexMonoNerdFontComplete-Bold
bold_font auto 
#italic_font Perplexed-BoldItalic 
italic_font BlexMonoNerdFontComplete-Bold
bold_italic_font auto

enable_audio_bell no

window_padding_width 20 
allow_remote_control yes

# OPACITY ###############################################
map kitty_mod+j    set_background_opacity -0.01
map kitty_mod+k    set_background_opacity +0.01
map kitty_mod+l    set_background_opacity 1
map kitty_mod+0    set_background_opacity default
dynamic_background_opacity yes
background_opacity 0.85
########################################################

font_size 12.0

map ctrl+shift+equal change_font_size all +0.5
map ctrl+shift+minus change_font_size all -0.5

background #121212
foreground #a0a0a0
cursor #bbbbbb
selection_background #453a39
color0 #1b1d1e
color8 #505354
color1 #f92672
color9 #ff669d
color2 #a6e22e
color10 #beed5f
color3 #fd971f
color11 #e6db74
color4 #66d93f
color12 #669943
color5 #9e6ffe
color13 #9e6ffe
color6 #5e7175
color14 #a3babf
color7 #ccccc6
color15 #f8f8f2
selection_foreground #121212
