include rose-pine-dawn.conf
map ctrl+b combine : clear_terminal active : send_text normal \x0c
resize_in_steps yes

enable_audio_bell no

allow_remote_control socket-only
shell_integration enabled
listen_on unix:/tmp/kitty

# TEXT ##################################################
font_family IBM Plex Mono Regular
font_size 23.5
shell_integration no-cursor
cursor_shape block
#adjust_line_height 150%
map ctrl+shift+equal change_font_size all +0.5
map ctrl+shift+minus change_font_size all -0.5
#########################################################

# OPACITY ###############################################
background_opacity 1
dynamic_background_opacity yes
map kitty_mod+j    set_background_opacity -0.01
map kitty_mod+k    set_background_opacity +0.01
map kitty_mod+l    set_background_opacity 1
map kitty_mod+0    set_background_opacity default
########################################################

scrollback_pager_history_size 10


# kitty-scrollback.nvim Kitten alias
action_alias kitty_scrollback_nvim kitten /Users/kaydemir/.local/share/nvim/lazy/kitty-scrollback.nvim/python/kitty_scrollback_nvim.py
 
# Browse scrollback buffer in nvim
map kitty_mod+h kitty_scrollback_nvim
# Browse output of the last shell command in nvim
map kitty_mod+g kitty_scrollback_nvim --config ksb_builtin_last_cmd_output
# Show clicked command output in nvim
mouse_map ctrl+shift+right press ungrabbed combine : mouse_select_command_output : kitty_scrollback_nvim --config ksb_builtin_last_visited_cmd_output



# BEGIN_KITTY_THEME
# 1984 Dark
include current-theme.conf
# END_KITTY_THEME
